"""
Kustomize Generator - Generates kustomization.yaml and patch files.
"""

import os
import logging
from pathlib import Path
from typing import List, Dict

import yaml

logger = logging.getLogger(__name__)


class KustomizeGenerator:
    """Generates Kustomize overlay files from patches."""
    
    def export(self, patches: List[Dict], output_path: str):
        """
        Export patches as Kustomize overlay.
        
        Args:
            patches: List of patch dictionaries
            output_path: Directory to write files
        
        Creates:
            output_path/
            ├── kustomization.yaml
            └── patches/
                ├── deployment-api.yaml
                ├── deployment-web.yaml
                └── ...
        """
        output_dir = Path(output_path)
        patches_dir = output_dir / "patches"
        
        # Create directories
        output_dir.mkdir(parents=True, exist_ok=True)
        patches_dir.mkdir(exist_ok=True)
        
        # Track patch files for kustomization.yaml
        patch_files = []
        
        # Write patch files
        for patch in patches:
            filename = f"{patch['name']}.yaml"
            filepath = patches_dir / filename
            
            with open(filepath, 'w') as f:
                yaml.dump(patch['patch'], f, default_flow_style=False)
            
            patch_files.append(f"patches/{filename}")
            logger.info(f"   📄 Created {filepath}")
        
        # Generate kustomization.yaml
        kustomization = {
            "apiVersion": "kustomize.config.k8s.io/v1beta1",
            "kind": "Kustomization",
            "resources": [
                "../../base"  # Reference to base manifests
            ],
            "patches": [
                {"path": pf} for pf in patch_files
            ]
        }
        
        kustomization_path = output_dir / "kustomization.yaml"
        with open(kustomization_path, 'w') as f:
            yaml.dump(kustomization, f, default_flow_style=False)
        
        logger.info(f"   📄 Created {kustomization_path}")
        
        # Also create a README
        readme_path = output_dir / "README.md"
        with open(readme_path, 'w') as f:
            f.write(self._generate_readme(patches))
        
        logger.info(f"   📄 Created {readme_path}")
    
    def _generate_readme(self, patches: List[Dict]) -> str:
        """Generate a README for the overlay."""
        lines = [
            "# Kustomize Overlay",
            "",
            "Generated by AI Kustomize Agent",
            "",
            "## Patches Applied",
            "",
        ]
        
        for patch in patches:
            lines.append(f"- **{patch['name']}** ({patch['namespace']})")
        
        lines.extend([
            "",
            "## Usage",
            "",
            "```bash",
            "# Preview",
            "kubectl kustomize .",
            "",
            "# Apply",
            "kubectl apply -k .",
            "```",
        ])
        
        return "\n".join(lines)
